# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rckni_R0XImDAQPlUuHdBCWXw9IVekQ7
"""

import simpledorff
import pandas as pd
import numpy as np

Data = pd.read_csv('hardly_human_!_annotations.csv');

newData1 = Data[["tweet_ID", "annotator_1"]].dropna().reset_index()
newData1 = newData1.rename(columns={'annotator_1': 'annotation'})
newData1["annotator_id"] = "annotator_1";

newData2 = Data[["tweet_ID", "annotator_2"]].dropna().reset_index()
newData2 = newData2.rename(columns={'annotator_2': 'annotation'})
newData2["annotator_id"] = "annotator_2";

newData3 = Data[["tweet_ID", "annotator_3"]].dropna().reset_index()
newData3 = newData3.rename(columns={'annotator_3': 'annotation'})
newData3["annotator_id"] = "annotator_3";

list = [newData1, newData2, newData3]

finalData= pd.concat(list, axis=0)

alpha_value = simpledorff.calculate_krippendorffs_alpha_for_df(finalData,experiment_col='tweet_ID',
                                                 annotator_col='annotator_id',
                                                 class_col='annotation')

print(alpha_value)